### PR TITLE
Dockerize project to make development easier

### LINKED ISSUE #3: Dockerize project to make development easier
### Motivation
It's need to make easier to contribute to `heartcheck-cas`!

Dockerizing it is a good start, it'll give a consistent and isolated environment.

**DOD**

- Must use the most possible updated Ruby version;
- Must pass all tests;
- README must be updated to include the recently updates.

### PR DESCRIPTION
**Pull request by m8051**
## Description

This PR attempts to Dockerize the project to make development easier by:
 - Using docker-compose to run the latest version of Ruby and the application in a Docker container.
 - Using a BootStrap Script written in Bash based on the [heartcheck script](https://github.com/locaweb/heartcheck/blob/master/scripts/heartcheck) to speed up common Docker tasks and go straight to the point, start developing
   - Add the option **[stop](https://github.com/locaweb/heartcheck-cas/compare/master...m8051:issues/3?expand=1#diff-697f8dc2962357e0c9c24f6b134828ec8ec8449e25af91ff927b687e2935f08dR42)**, to start the development environment with a clean state. (might be helpful in some scenarios)
- Updating documentation with the latest changes
  - README.md
  - CHANGELOG.md
 
## Feature
Resolves https://github.com/locaweb/heartcheck-cas/issues/3

## Type of change
 - [X] New feature (non-breaking change which adds functionality)
 - [X] This change requires a documentation update
 
## How Has This Been Tested?
By executing the script arguments
 - [X] Run script arguments { bash | bundle | rspec | setup | stop }.
 
## Checklist
- [X] Adds docker-compose file;
- [X] Adds bash script;
- [X] Updates documentation.

### CODE REVIEW

**Review by VictorSNA — CHANGES_REQUESTED** [review]
Hey! Thanks for your collaboration!

Please, fix sourcelevel-bot comments then I can approve your PR! :)

**Comment by m8051** [comment]
@VictorSNA I tried to fix most of the syntax issues in both files README.md and CHANGELOG.md but was not capable to fix these:

```md
CHANGELOG.md
    6:4-6:11  warning  Found reference to undefined definition  no-undefined-references  remark-lint
  10:4-10:11  warning  Found reference to undefined definition  no-undefined-references  remark-lint
  16:4-16:11  warning  Found reference to undefined definition  no-undefined-references  remark-lint
```

I looked at what they are and it seems we might want to update the syntax according to this [link](https://unifiedjs.com/explore/package/remark-lint-no-undefined-references/)

What do you want me to do for these warnings?

Thanks

**Review by VictorSNA — APPROVED** [review]
Hey! Nice job! Thanks for solving the sourcelevel requests!

**Comment by m8051** [comment]
> Hey! Nice job! Thanks for solving the sourcelevel requests!

Thanks to you @VictorSNA for reviewing and approving it. Happy to help you out

**Comment by TecnoSigma** [comment]
Tks @m8051 :slightly_smiling_face:

**Review by TecnoSigma — APPROVED** [review]

**Pull request merged**
